const foodItems = [
  {
    id: 1,
    category: "Desserts",
    name: "Chocolate Lava Cake",
    ingredients: [
      "1/2 cup unsalted butter",
      "4 oz dark chocolate, chopped",
      "1 cup powdered sugar",
      "2 large eggs",
      "2 large egg yolks",
      "1 tsp vanilla extract",
      "1/2 cup all-purpose flour",
      "Pinch of salt",
    ],
    preparationInstructions: [
      "Preheat oven to 425°F (220°C). Grease 4 ramekins and place on a baking sheet.",
      "Melt the butter and chocolate in a microwave-safe bowl, stirring until smooth.",
      "Stir in the powdered sugar until well combined.",
      "Whisk in the eggs, egg yolks, and vanilla extract.",
      "Fold in the flour and salt until just combined.",
      "Divide the batter evenly among the ramekins.",
      "Bake for 12-14 minutes, until the edges are firm but the centers are still soft.",
      "Let cool for 1 minute, then run a knife around the edges to loosen and invert onto plates.",
      "Serve warm with ice cream or whipped cream.",
    ],
    price: "$6.00",
    image:
      "https://images.pexels.com/photos/1126359/pexels-photo-1126359.jpeg?auto=compress&cs=tinysrgb&w=400",
  },
  {
    id: 2,
    category: "Breakfast",
    name: "Avocado Toast",
    ingredients: [
      "1 ripe avocado",
      "2 slices of whole grain bread",
      "1 tbsp olive oil",
      "1/2 tsp sea salt",
      "1/4 tsp black pepper",
      "1/4 tsp red pepper flakes",
      "1 tsp lemon juice",
      "Optional toppings: cherry tomatoes, radishes, microgreens",
    ],
    preparationInstructions: [
      "Toast the bread slices to your desired level of crispiness.",
      "While the bread is toasting, cut the avocado in half, remove the pit, and scoop the flesh into a bowl.",
      "Mash the avocado with a fork, mixing in the olive oil, sea salt, black pepper, red pepper flakes, and lemon juice.",
      "Spread the mashed avocado evenly onto the toasted bread slices.",
      "Add any optional toppings as desired.",
      "Serve immediately.",
    ],
    price: "$4.50",
    image: "https://example.com/avocado_toast.jpg",
  },
  {
    id: 3,
    category: "Dinner",
    name: "Grilled Salmon",
    ingredients: [
      "4 salmon fillets",
      "2 tbsp olive oil",
      "1 tbsp lemon juice",
      "2 cloves garlic, minced",
      "1 tsp salt",
      "1/2 tsp black pepper",
      "1 tbsp fresh dill, chopped",
      "Lemon wedges, for serving",
    ],
    preparationInstructions: [
      "Preheat the grill to medium-high heat.",
      "In a small bowl, whisk together the olive oil, lemon juice, garlic, salt, and pepper.",
      "Brush the salmon fillets with the mixture, ensuring they are well coated.",
      "Place the salmon fillets on the grill, skin side down, and cook for 4-5 minutes per side, or until the salmon is opaque and flakes easily with a fork.",
      "Remove from the grill and sprinkle with fresh dill.",
      "Serve with lemon wedges.",
    ],
    price: "$15.00",
    image:
      "https://www.thecookierookie.com/wp-content/uploads/2023/05/grilled-salmon-recipe-2-960x1200.jpg",
  },
  {
    id: 4,
    category: "Vegetarian",
    name: "Veggie Stir-Fry",
    ingredients: [
      "2 tbsp vegetable oil",
      "1 red bell pepper, sliced",
      "1 yellow bell pepper, sliced",
      "1 broccoli head, cut into florets",
      "1 carrot, sliced",
      "1 zucchini, sliced",
      "2 cloves garlic, minced",
      "1 tbsp soy sauce",
      "1 tbsp hoisin sauce",
      "1 tsp sesame oil",
      "1 tsp cornstarch mixed with 2 tbsp water",
      "Cooked rice, for serving",
    ],
    preparationInstructions: [
      "Heat the vegetable oil in a large skillet or wok over medium-high heat.",
      "Add the garlic and stir-fry for 30 seconds until fragrant.",
      "Add the bell peppers, broccoli, carrot, and zucchini to the skillet. Stir-fry for 5-7 minutes until the vegetables are tender-crisp.",
      "In a small bowl, mix the soy sauce, hoisin sauce, sesame oil, and cornstarch mixture.",
      "Pour the sauce over the vegetables and stir to coat.",
      "Cook for another 1-2 minutes until the sauce has thickened.",
      "Serve the stir-fry over cooked rice.",
    ],
    price: "$8.00",
    image: "https://example.com/veggie_stir_fry.jpg",
  },
  {
    id: 5,
    category: "Seafood",
    name: "Shrimp Scampi",
    ingredients: [
      "1 lb large shrimp, peeled and deveined",
      "3 tbsp unsalted butter",
      "2 tbsp olive oil",
      "4 cloves garlic, minced",
      "1/4 tsp red pepper flakes",
      "1/4 cup dry white wine",
      "1 tbsp lemon juice",
      "1/4 cup chopped parsley",
      "Salt and pepper, to taste",
      "Cooked pasta, for serving",
    ],
    preparationInstructions: [
      "Heat the butter and olive oil in a large skillet over medium-high heat.",
      "Add the garlic and red pepper flakes, and sauté for 1 minute until fragrant.",
      "Add the shrimp and cook for 2-3 minutes on each side until pink and opaque.",
      "Remove the shrimp from the skillet and set aside.",
      "Add the white wine and lemon juice to the skillet, scraping up any browned bits from the bottom.",
      "Simmer for 2 minutes, then return the shrimp to the skillet.",
      "Toss the shrimp in the sauce and sprinkle with chopped parsley.",
      "Season with salt and pepper to taste.",
      "Serve over cooked pasta.",
    ],
    price: "$12.00",
    image: "https://example.com/shrimp_scampi.jpg",
  },
  {
    id: 6,
    category: "Street Food",
    name: "Tacos",
    ingredients: [
      "1 lb ground beef or chicken",
      "1 packet taco seasoning",
      "1/2 cup water",
      "8 small corn or flour tortillas",
      "1 cup shredded lettuce",
      "1 cup diced tomatoes",
      "1/2 cup shredded cheese",
      "1/4 cup sour cream",
      "1/4 cup salsa",
    ],
    preparationInstructions: [
      "Cook the ground beef or chicken in a large skillet over medium heat until browned and cooked through.",
      "Drain any excess fat.",
      "Add the taco seasoning and water to the skillet, stirring to combine.",
      "Simmer for 5 minutes until the sauce has thickened.",
      "Warm the tortillas in a dry skillet or microwave.",
      "Fill each tortilla with the seasoned meat, shredded lettuce, diced tomatoes, shredded cheese, sour cream, and salsa.",
      "Serve immediately.",
    ],
    price: "$10.00",
    image: "https://example.com/tacos.jpg",
  },
];

export default foodItems;
